# This is a basic workflow that is manually triggered

name: Do nothing

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  blah:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: noop
        run: ":"
